### ISSUE TITLE
File paths in manifest are altered on commit

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/workflow_colony_formation#1]
The file paths that `datastep` stores in the manifest are stripped of their `/localhost/step` prefix on commit to Quilt. A workaround is to look for these paths and insert where needed, depending on if the relevant precursor step was run locally or has been checked out from quilt. This needs to be applied to all existing steps.

**Comment by evamaxfield** [comment]
I was notified by email of this. I _think_ you are saying "need to fix the paths as they are stored in quilt to be absolute to local machine and vice versa". We thought of that pretty early on and wrote two functions but unfortunately they aren't exposed except in pure Python.

```python
from actk.steps import StandardizeFOVArray
s = StandardizeFOVArray()
s.manifest_filepaths_rel2abs()
```

**Comment by evamaxfield** [comment]
To do the reverse its simply `manifest_filepaths_abs2rel()`
